version: '2'
networks:
  main:
services:
  mongo:
    image: mongo:3.4.23
    container_name: microcks-mongo
    volumes:
      - "~/tmp/microcks-data:/data/db"
    networks:
      main:
        aliases:
          - mongo
  postman:
    image: quay.io/microcks/microcks-postman-runtime:latest
    container_name: microcks-postman-runtime
    networks:
      main:
        aliases:
          - postman
  keycloak:
    image: jboss/keycloak:9.0.2
    command: "-b 0.0.0.0 -Dkeycloak.import=/microcks-keycloak-config/microcks-realm-sample.json"
    container_name: microcks-keycloak
    ports:
      - "8180:8080"
      - "8543:8443"
    volumes:
      - ./keycloak-realm:/microcks-keycloak-config
      - ./keystore:/etc/x509/https
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "123"
    networks:
      main:
        aliases:
          - keycloak
  app:
    depends_on:
      - mongo
      - postman
      - keycloak
    image: quay.io/microcks/microcks:nightly
    container_name: microcks
    volumes:
      - ./config:/deployments/config
      - ./keystore:/deployments/keystore
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
      - SPRING_DATA_MONGODB_DATABASE=microcks
      - POSTMAN_RUNNER_URL=http://postman:3000
      - TEST_CALLBACK_URL=http://microcks:8080
      #- KEYCLOAK_URL=https://localhost:8543/auth
      - SERVICES_UPDATE_INTERVAL=0 0 0/2 * * *
      - KEYCLOAK_URL=https://docker.for.mac.localhost:8543/auth
      #- KEYCLOAK_URL=https://docker.for.win.localhost:8543/auth
    networks:
      main:
        aliases:
          - microcks