kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Values.appName }}"
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  {{- with .Values.microcks.ingressAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: "{{ .Values.appName }}"
    group: microcks
spec:
  tls:
  - hosts:
    - "{{ .Values.microcks.url }}"
    secretName: {{ .Values.microcks.ingressSecretRef | default (print .Values.appName "-microcks-ingress-secret") }}
  rules:
  - host: "{{ .Values.microcks.url }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.appName }}"
            port:
              number: 8080
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Values.appName }}-grpc"
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  {{- with .Values.microcks.grpcIngressAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: "{{ .Values.appName }}"
    group: microcks
spec:
  tls:
  - hosts:
     - {{ ( include "microcks-grpc.url" . ) }}
  rules:
  - host: {{ ( include "microcks-grpc.url" . ) }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.appName }}-grpc"
            port:
              number: 9090
{{- if .Values.keycloak.install }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Values.appName }}-keycloak"
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  {{- with .Values.keycloak.ingressAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: "{{ .Values.appName }}"
    group: microcks
spec:
  tls:
  - hosts:
    - "{{ .Values.keycloak.url }}"
    secretName: {{ .Values.keycloak.ingressSecretRef | default (print .Values.appName "-keycloak-ingress-secret") }}
  rules:
  - host: "{{ .Values.keycloak.url }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.appName }}-keycloak"
            port:
              number: 8080
{{- end }}
{{- if and .Values.features.async.enabled }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Values.appName }}-ws"
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3000"
  {{- with .Values.features.async.ws.ingressAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: "{{ .Values.appName }}"
    group: microcks
spec:
  tls:
  - hosts:
    - "{{ ( include "microcks-ws.url" . ) }}"
    secretName: {{ .Values.features.async.ws.ingressSecretRef | default (print .Values.appName "-microcks-ws-ingress-secret") }}
  rules:
  - host: "{{ ( include "microcks-ws.url" . ) }}"
    http:
      paths:
        - path: /api/ws
          pathType: Prefix
          backend:
            service:
              name: "{{ .Values.appName }}-async-minion"
              port:
                number: 8080
{{- end }}