apiVersion: v2
name: microcks
version: 1.9.0
kubeVersion: '>=1.17.0-0'
description: Microcks - API Mocking and Testing
type: application
keywords:
  - mocks
  - microservice
  - api
  - test
home: https://microcks.io
sources:
  - http://github.com/microcks/microcks/
  - https://microcks.io
maintainers:
  - name: Laurent Broudoux
    email: laurent.broudoux@gmail.com
icon: https://microcks.io/images/microcks-big.png
appVersion: 1.9.0
